version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: dilly_sports
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha_segura
      POSTGRES_DB: pi_primeiro_semestre
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  meu_pgadmin:
    image: dpage/pgadmin4
    container_name: meu_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: senha_segura
      PGADMIN_CONFIG_SERVER_MODE: 'True'
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres-db

volumes:
  postgres_data:
  pgadmin_data: