@startuml

header Engenharia de Software - Casos de Uso
title Diagrama de Casos de Uso - Manutencao Industrial

left to right direction

skinparam usecaseBackgroundColor #FFFFCC
skinparam usecaseBorderColor #993333
skinparam usecaseArrowColor #993333
skinparam actorBackgroundColor #FFEEEE
skinparam actorBorderColor #993333
skinparam rectangleBackgroundColor #FFFFFF
skinparam rectangleBorderColor #993333

actor "Solicitante" as S
actor "Tecnico"     as T
actor "Gestor"      as G

G -up-|> S

rectangle "Sistema de Gestao de Manutencao" {

    usecase "Autenticar no Sistema"                         as UC_LOGIN

    usecase "Abrir Ordem de Servico"                        as UC01
    usecase "Listar e Filtrar OS"                           as UC_LIST
    usecase "Acompanhar Status da OS"                       as UC_ACOMP
    usecase "Cadastrar Equipamento"                         as UC_CAD_EQUIP
    usecase "Designar Tecnico para OS"                      as UC02
    usecase "Atualizar Status da OS"                        as UC03
    usecase "Encerrar OS com Relatorio Tecnico"             as UC_CLOSE
    usecase "Cancelar OS"                                   as UC_CANCEL
    usecase "Definir ou Alterar Prioridade da OS"           as UC_PRIO

    usecase "Registrar Uso de Ferramenta"                   as UC04
    usecase "Devolver Ferramenta"                           as UC_DEV_FERR
    usecase "Registrar Pecas Utilizadas"                    as UC_PECAS

    usecase "Consultar Historico de Equipamento"            as UC05
    usecase "Consultar Historico do Setor"                  as UC_HIST_SET
    usecase "Registrar Historico de Alteracoes"             as UC_HIST_OS

    usecase "Visualizar Dashboard de Metricas e Relatorios" as UC06
    usecase "Gerar Relatorio por Periodo"                   as UC_REL

    usecase "Manter Usuarios e Tecnicos"                    as UC_MAN_USER
    usecase "Gerenciar Estoque de Pecas"                    as UC_ESTOQUE

    UC01        <.. UC_CAD_EQUIP : <<extend>>
    UC03        <.. UC_CLOSE     : <<extend>>
    UC03        <.. UC_CANCEL    : <<extend>>
    UC02        <.. UC_PRIO      : <<extend>>

    UC04        ..> UC03         : <<include>>
    UC_DEV_FERR ..> UC04         : <<include>>
    UC_PECAS    ..> UC03         : <<include>>
    UC03        ..> UC_HIST_OS   : <<include>>
    UC_CLOSE    ..> UC03         : <<include>>

    UC01        ..> UC_LOGIN     : <<include>>
    UC02        ..> UC_LOGIN     : <<include>>
    UC03        ..> UC_LOGIN     : <<include>>
    UC04        ..> UC_LOGIN     : <<include>>
    UC05        ..> UC_LOGIN     : <<include>>
    UC06        ..> UC_LOGIN     : <<include>>
    UC_MAN_USER ..> UC_LOGIN     : <<include>>
}

S --> UC01
S --> UC_LIST
S --> UC_ACOMP
S --> UC_HIST_SET

T --> UC03
T --> UC04
T --> UC_DEV_FERR
T --> UC_PECAS
T --> UC05
T --> UC_HIST_OS

G --> UC02
G --> UC_PRIO
G --> UC05
G --> UC_HIST_SET
G --> UC06
G --> UC_REL
G --> UC_MAN_USER
G --> UC_ESTOQUE

@enduml